apiVersion: v1
kind: Pod
metadata:
  name: docker-with-git
spec:
  restartPolicy: OnFailure
  containers:
    - name: docker-with-git
      image: "docker:git"
      # Just spin & wait forever
      command: [ "tail", "-f", "/dev/null" ]
