apiVersion: v1
kind: Pod
metadata:
  name: docker-with-git
spec:
  restartPolicy: OnFailure
  containers:
    - name: docker-with-git
      image: "docker:git"
      # Just spin & wait forever
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      resources:
        limits:
          nvidia.com/gpu: 1
