apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-with-cuda
spec:
  restartPolicy: OnFailure
  containers:
    - name: ubuntu-with-cuda
      image: "nvidia/cuda:11.8.0-base-ubuntu22.04"
      command: ["while true; do sleep 1; done"]
      resources:
        limits:
          nvidia.com/gpu: 1
