apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-with-cuda
spec:
  restartPolicy: OnFailure
  containers:
    - name: ubuntu-with-cuda
      image: "nvidia/cuda:11.8.0-base-ubuntu22.04"
      # Just spin & wait forever
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      resources:
        limits:
          nvidia.com/gpu: 1
