apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      image: "nvidia/cuda:11.8.0-base-ubuntu22.04"
      command: ["sleep infinity"]
      resources:
        limits:
          nvidia.com/gpu: 1
